import = [
  "~/.config/alacritty/themes/themes/rose-pine.toml",
  # "~/.config/alacritty/themes/themes/rose-pine-dawn.toml"
]

[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
dynamic_padding = true
decorations = "buttonless"
option_as_alt = "Both"
[window.dimensions]
columns = 120
lines = 60
[window.position]
x = 700
y = 600

[scrolling]
history = 23040

[font]
size = 15
[font.normal]
family = "BerkeleyMono Nerd Font Mono"
style = "Regular"
[font.bold]
family = "BerkeleyMono Nerd Font Mono"
[font.italic]
family = "BerkeleyMono Nerd Font Mono"
[font.offset]
x = 0
y = 2
[font.glyph_offset]
x = -1
y = -1

[bell]
animation = "EaseOutExpo"

[cursor.style]
shape = "Block"
[cursor.vi_mode_style]
blinking = "On"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
